version: '3.7'
services:
  php-cli:
    image: datadog-debugging:latest
    build:
      dockerfile: docker/Dockerfile
      context: .
    volumes:
      - .:/application
      - ./docker/99-ddtrace-custom.ini:/usr/local/etc/php/conf.d/99-ddtrace-custom.ini
      - ./docker/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
      - datadog_bridge:/opt/datadog-php/dd-trace-sources/bridge

volumes:
  datadog_bridge:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/alex/Projects/datadog-debugging/var/datadog_bridge'
